SELECT TABLE_NAME
    ,COLUMN_NAME
    ,ORDINAL_POSITION
    ,COLUMN_HASDEFAULT
    ,COLUMN_DEFAULT
    ,DATA_TYPE
    ,CHARACTER_MAXIMUM_LENGTH
    ,CHARACTER_OCTET_LENGTH
    ,NUMERIC_PRECISION
    ,NUMERIC_SCALE
    ,DATETIME_PRECISION
    ,IS_NULLABLE
    ,AUTOINC_INCREMENT
FROM INFORMATION_SCHEMA.COLUMNS
ORDER BY TABLE_NAME, ORDINAL_POSITION;