SELECT
	INFORMATION_SCHEMA.COLUMNS.*,
	COL_LENGTH(TABLE_SCHEMA + '.' + TABLE_NAME, INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME) AS COLUMN_LENGTH,
	COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsComputed') AS IsComputed,
	COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsIdentity') AS IsIdentity,
	COLUMNPROPERTY(OBJECT_ID(TABLE_SCHEMA + '.' + TABLE_NAME), INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME, 'IsRowGuidCol') AS IsRowGuidCol,
	exDescription.Value AS Description
FROM
	INFORMATION_SCHEMA.COLUMNS
	LEFT JOIN ::fn_listextendedproperty('MS_Description', 'user', '#TableSchema#', 'table', '#TableName#', 'column', default) AS exDescription
	    ON INFORMATION_SCHEMA.COLUMNS.COLUMN_NAME collate SQL_Latin1_General_CP1_CI_AS = exDescription.objName collate SQL_Latin1_General_CP1_CI_AS
WHERE
	INFORMATION_SCHEMA.COLUMNS.TABLE_SCHEMA = '#TableSchema#'
	AND INFORMATION_SCHEMA.COLUMNS.TABLE_NAME = '#TableName#'
